### ISSUE TITLE
Minor Issue: <input-path-list> needs to include file name input.csv

### ISSUE THREAD

**Issue by danindiana** [fengju514/Expression-Net#12]
Trying to run the program via the directions returns error:

$ python main_ExpShapePoseNet.py /home/johnh/gits/Expression-Net/
> make dir
Traceback (most recent call last):
  File "main_ExpShapePoseNet.py", line 280, in <module>
    tf.app.run()
  File "/home/johnh/gits/Expression-Net/venv/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main_ExpShapePoseNet.py", line 276, in main
    extract_PSE_feats()
  File "main_ExpShapePoseNet.py", line 73, in extract_PSE_feats
    data_dict = myparse.parse_input(inputlist) # please see input.csv for the input format
  File "/home/johnh/gits/Expression-Net/myparse.py", line 5, in parse_input
    reader = csv.DictReader(open(input_file,'r'))

Suggest modifying program to search for input.csv file and/or changing quickstart directions to include path-to-file and file-name. Modifying data_dict = myparse.parse_input(inputlist) to simply grab whatever .csv file is found in directory might also work but I'm not knowledgeable enough python user to implement.

**Comment by Dieskiz** [comment]
have you solved this issues yet? becuase i'm having this error:

> make dir
usage: main_ExpShapePoseNet.py [-h] input_list_path
main_ExpShapePoseNet.py: error: the following arguments are required: input_list_path
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

it's very similiar to mine, please provide help ASAP
